config/routes.rb
Caviar::Application.routes.draw do
  root 'main#index'
  resources :variants
  resources :dropdowns
  resources :items

  

end

app/models/dropdown.rb
class Dropdown < ActiveRecord::Base
  belongs_to :item
  has_many :variants
  validates :name, presence: :true
  validates :item_id, presence: :true
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :dropdowns
  validates :name, presence: :true, uniqueness: { case_sensitive: :false }
end

app/models/variant.rb
class Variant < ActiveRecord::Base
  belongs_to :dropdown
  validates :name, presence: :true
  validates :dropdown_id, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dropdowns_controller.rb
class DropdownsController < ApplicationController
  def index
    @dropdowns = Dropdown.all
  end

  def show
    @dropdown = Dropdown.find(params[:id])
  end

  def new
    @dropdown = Dropdown.new
  end

  def create
    @dropdown = Dropdown.new(dropdown_parameters)
    if @dropdown.save
      redirect_to @dropdown, :notice => "Successfully created dropdown."
    else
      render :action => 'new'
    end
  end

  def edit
    @dropdown = Dropdown.find(params[:id])
  end

  def update
    @dropdown = Dropdown.find(params[:id])
    if @dropdown.update_attributes(dropdown_parameters)
      redirect_to @dropdown, :notice  => "Successfully updated dropdown."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @dropdown = Dropdown.find(params[:id])
    @dropdown.destroy
    redirect_to dropdowns_url, :notice => "Successfully destroyed dropdown."
  end
  private
  def dropdown_parameters
    params.require(:dropdown).permit(:name, :item_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_parameters)
    if @item.save
      redirect_to @item, :notice => "Successfully created item."
    else
      render :action => 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(item_parameters)
      redirect_to @item, :notice  => "Successfully updated item."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_url, :notice => "Successfully destroyed item."
  end

  private
  def item_parameters
    params.require(:item).permit(:name, :comment, :private, :price)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  
  end
end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
  def index
    @variants = Variant.all
  end

  def show
    @variant = Variant.find(params[:id])
  end

  def new
    @variant = Variant.new
  end

  def create
    @variant = Variant.new(variant_parameters)
    if @variant.save
      redirect_to @variant, :notice => "Successfully created variant."
    else
      render :action => 'new'
    end
  end

  def edit
    @variant = Variant.find(params[:id])
  end

  def update
    @variant = Variant.find(params[:id])
    if @variant.update_attributes(variant_parameters)
      redirect_to @variant, :notice  => "Successfully updated variant."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @variant = Variant.find(params[:id])
    @variant.destroy
    redirect_to variants_url, :notice => "Successfully destroyed variant."
  end
  private
  def variant_parameters
    params.require[:variant].permit(:name, :dropdown_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dropdowns_helper.rb
module DropdownsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/dropdowns/_form.html.erb
<%= form_for @dropdown do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :item %><br />
    <%= f.select(:item_id, Item.all.collect { |p| [p.name, p.id] }) %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/dropdowns/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @dropdown %> |
  <%= link_to "View All", dropdowns_path %>
</p>

app/views/dropdowns/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Item</th>
  </tr>
  <% for dropdown in @dropdowns %>
    <tr>
      <td><%= dropdown.name %></td>
      <td><%= dropdown.item_id %></td>
      <td><%= link_to "Show", dropdown %></td>
      <td><%= link_to "Edit", edit_dropdown_path(dropdown) %></td>
      <td><%= link_to "Destroy", dropdown, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Dropdown", new_dropdown_path %></p>

app/views/dropdowns/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", dropdowns_path %></p>

app/views/dropdowns/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @dropdown.name %>
</p>
<p>
  <strong>Item:</strong>
  <%= @dropdown.item_id %>
</p>

<p>
  <%= link_to "Edit", edit_dropdown_path(@dropdown) %> |
  <%= link_to "Destroy", @dropdown, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", dropdowns_path %>
</p>

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </p>
  <p>
    <%= f.label :private %><br />
    <%= f.check_box :private %>
  </p>
  <p>
    <%= f.label :price %><br/>
    <%= f.text_field :price %><br/>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/items/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @item %> |
  <%= link_to "View All", items_path %>
</p>

app/views/items/index.html.erb
<div class="items">
  <table>
    <tr>
      <th>Name</th>
      <th>Comment</th>
      <th>Private</th>
      <th>Price</th>
    </tr>
    <% for item in @items %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.comment %></td>
        <td><%= item.private %></td>
        <td><%= item.price %></td>
        <td><%= link_to "Show", item %></td>
        <td><%= link_to "Edit", edit_item_path(item) %></td>
        <td><%= link_to "Destroy", item, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
  </table>

  <p><%= link_to "New Item", new_item_path %></p>
</div>

app/views/items/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", items_path %></p>

app/views/items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <%= link_to "Edit", edit_item_path(@item) %> |
  <%= link_to "Destroy", @item, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", items_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Caviar</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="root_link">
  <%= link_to "Strona główna", root_path %>
</div>
<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<%= link_to "Items", items_path %><br/>
<%= link_to "Dropdowns",dropdowns_path %><br/>
<%= link_to "Variants",variants_path %><br/>

app/views/variants/_form.html.erb
<%= form_for @variant do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :dropdown_id %><br />
    <%= f.select(:dropdown_id, Dropdown.all.collect{ |p| [p.name, p.id] }) %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/variants/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @variant %> |
  <%= link_to "View All", variants_path %>
</p>

app/views/variants/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Dropdown</th>
  </tr>
  <% for variant in @variants %>
    <tr>
      <td><%= variant.name %></td>
      <td><%= variant.dropdown_id %></td>
      <td><%= link_to "Show", variant %></td>
      <td><%= link_to "Edit", edit_variant_path(variant) %></td>
      <td><%= link_to "Destroy", variant, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Variant", new_variant_path %></p>

app/views/variants/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", variants_path %></p>

app/views/variants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @variant.name %>
</p>
<p>
  <strong>Dropdown:</strong>
  <%= @variant.dropdown_id %>
</p>

<p>
  <%= link_to "Edit", edit_variant_path(@variant) %> |
  <%= link_to "Destroy", @variant, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", variants_path %>
</p>